name: 'wp-plugin-check-tests'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
    - main

jobs:
  wp-plugin-check-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Run plugin check
      uses: swissspidy/wp-plugin-check-action@v1
      # Parameter documentation:
      # https://github.com/swissspidy/wp-plugin-check-action#usage
      with:
        # build-dir: './my-awesome-plugin'
        exclude-directories: 'vendor,node_modules'
